apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-app
  template:
    metadata:
      labels:
        app: tasks-app
    spec:
      containers:
        - name: tasks-container
          image: docentcafedry/tasks:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service-service.default"
            - name: TASKS_FOLDER
              value: "tasks"